# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_maingui(object):
    def setupUi(self, maingui):
        maingui.setObjectName("maingui")
        maingui.resize(372, 207)
        self.label = QtWidgets.QLabel(maingui)
        self.label.setGeometry(QtCore.QRect(-10, -10, 391, 221))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/Downloads/J_A_R_V_I_S_live_wallpaper.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.retranslateUi(maingui)
        QtCore.QMetaObject.connectSlotsByName(maingui)

    def retranslateUi(self, maingui):
        _translate = QtCore.QCoreApplication.translate
        maingui.setWindowTitle(_translate("maingui", "maingui"))
import gui_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    maingui = QtWidgets.QWidget()
    ui = Ui_maingui()
    ui.setupUi(maingui)
    maingui.show()
    sys.exit(app.exec_())
